dataset_type: neural_graph_mapping.slam_datasets.kintinuous_dataset.KintinuousDataset
dataset_config:
  root_dir: ~/.neural_graph_mapping/datasets/kintinuous/
  scene: loop
  slam_final_file: null
  slam_c2w_file: orbslam2_c2w.json
  slam_pg_file: orbslam2_pg.json
  fps: 30
  frame_skip: 0  # 0 means all frames are used, 1 every other, 2 every third, ...
  scale: 1
  prefetch: False
  device: cpu
  up_axis: -y  # used for visualization
  camera:
    width: 640
    height: 480
    fx: 528.01442863461716 
    fy: 528.01442863461716 
    cx: 320
    cy: 257
    pixel_center: 0.5
